# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_usercheckout_braintree_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercheckout',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
