# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170823_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid')], default='created', max_length=120),
        ),
    ]
