# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170808_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='This slug'),
        ),
    ]
